spring:
  data:
      mongodb:
        uri: mongodb+srv://mananshah:manan123@cluster0.iqwu6.mongodb.net/test
        database: tweetapp
  application:
    name: TweetAppService
      
logging:
  file:
    path: './config/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
client:
  url: http://localhost:4200
